name: BetterGameMode
main: GamerMJay\BetterGM\Main
api: [4.0.0]
description: Easy GameMode plugin
version 1.0.0

commands:
gm0:
 description: Go to survival mode
 permission: gm0.use
gm1:
 description: Go to creative mode
 permission: gm1.use
gm2:
 description: Go to adventure mode
 permission: gm2.use
gm3:
 description: Go to spectator mode
 permission: gm3.use

permissions:
gm0.use:
 default: op
gm1.use:
 default: op
gm2.use:
 default: op
gm3.use:
 default: op
