---
name: BetterGameMode
main: GamerMJay\BetterGameMode\Main
author: GamerMJay
api:
- 5.0.0
description: Easy GameMode plugin
version: 5.1.1
website: https://github.com/GamerMJay/BetterGameMode
permissions:
  bettergamemode.gmform:
    default: op
  bettergamemode.gm0:
    default: op
  bettergamemode.gm1:
    default: op
  bettergamemode.gm2:
    default: op
  bettergamemode.gm3:
    default: op
...
