---
name: BetterGameMode
main: GamerMJay\BetterGameMode\Main
author: GamerMJay
api:
- 4.0.0
description: Easy GameMode plugin
version: 5.1.0
website: https://github.com/GamerMJay/BetterGameMode
permissions:
  bettergameode.gmform:
    default: op
  bettergameode.gm0:
    default: op
  bettergameode.gm1:
    default: op
  bettergameode.gm2:
    default: op
  bettergameode.gm3:
    default: op
...
