---
name: BetterGameMode
main: GamerMJay\BetterGameMode\Main
author: GamerMJay
api:
- 5.0.0
description: Easy GameMode plugin
version: 4.0.0
website: https://github.com/GamerMJay/BetterGameMode
permissions:
  gm.use:
    default: op
  gm0.use:
    default: op
  gm1.use:
    default: op
  gm2.use:
    default: op
  gm3.use:
    default: op
...
