name: BetterGameMode
main: GamerMJay\BetterGameMode\Main
author: GamerMJay2008
api: 4.0.0
description: Easy GameMode plugin
version: 3.0.0
website: https://github.com/GamerMJay2008/BetterGameMode


permissions:
  gm.use:
    default: op
  gm0.use:
    default: op
  gm1.use:
    default: op
  gm2.use:
    default: op
  gm3.use:
    default: op
